name: docya_pro
description: Aplicación para médicos de DocYa Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


  
  


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0 
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  web_socket_channel: ^2.4.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  signature: ^5.4.0
  http_parser: ^4.0.2
  awesome_snackbar_content: ^0.1.3
  flutter_animate: ^4.3.0
  google_fonts: ^6.2.0
  card_swiper: ^3.0.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.1
  phosphor_flutter: ^2.1.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.2
  package_info_plus: ^8.0.0
  flutter_launcher_icons: ^0.14.4

  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_pdfview: ^1.3.2
  vibration: ^1.8.4
  audioplayers: ^6.1.0





flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logoblanco.png
    - assets/docyapro.png
    - assets/DOCYAPROBLANCO.png
    - assets/sounds/alert.mp3
    - assets/icons/icon.png



flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#14B8A6"
  adaptive_icon_foreground: "assets/icons/icon.png"



dependency_overrides:
  geolocator: ^12.0.0
  background_location: ^0.13.0
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  web_socket_channel: ^3.0.1
  
